### ISSUE TITLE
Next Article

### ISSUE THREAD

**Issue by pjebs** [ik5/gostrutils#18]
https://dev.to/ik5/golang-and-shared-objects-part-1-the-background-4ecf

Where can I find Parts 2-4 of your series?

**Comment by pjebs** [comment]
@ik5

**Comment by ik5** [comment]
Hi @pjebs 
I will write them, people were uninterested so I did not continue them.

**Comment by pjebs** [comment]
@ik5 You wrote:
```
On the next part I will start writing some code, providing examples on how to write shared library both using C and Go.

And on the 3rd part how to use them inside both C and Go.

The 4th part will explain how to create special cases of Shared libraries (e.g. Go's plugins).

```

Can you explain how Go's plugins are a special case of Shared libraries. That is what interest me the most (although I'm interested in all of the topics)

**Comment by ik5** [comment]
Sure I'll continue the entire subject including the `plugin` shared object.
